- type: job
  id: Antiquarian
  name: job-name-antiquarian
  description: job-description-antiquarian
  playTimeTracker: JobAntiquarian
  weight: 49
  startingGear: AntiquarianGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconAntiquarian"
  supervisors: job-supervisors-tap
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-antiquarian
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - Tradeband
          - OldTaypani
          - Freespeak
        addUnderstood:
          - Tradeband
          - OldTaypani
          - Freespeak
  access:
  - Families
  - Izdari
  - Command
  - Maintenance
  - Antiquarian
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AntiquarianGear
  equipment:
    id: AntiquarianPDA
    ears: ClothingHeadsetFamilies
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitAntiquarianFamilies
    back: BackpackAntiquarianSatchelFilled
