- type: job
  id: BeltrunnerTAP
  name: job-name-beltrunner
  description: job-description-beltrunner
  playTimeTracker:  JobBeltrunnerTAP
  weight: 4
  startingGear: BeltrunnerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconBeltrunner"
  supervisors: job-supervisors-tap
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-beltrunner
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - Tradeband
          - OldTaypani
          - Freespeak
        addUnderstood:
          - Tradeband
          - OldTaypani
          - Freespeak
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - Izdari
  - Families
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - External
  - Captain # Frontier

- type: startingGear
  id: BeltrunnerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBeltrunner
    back: ClothingBackpackSatchelFilled
    shoes: ClothingShoesBootsJack
    id: BeltrunnerPDA
    ears: ClothingHeadsetFamilies
    gloves: ClothingHandsGlovesFingerless
